apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: nexus-service
  labels:
    app: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      initContainers:
        - name: db-migration
          image: nexus/appointment-service:1.0-early
          command: ['bunx', 'prisma', 'migrate', 'deploy']
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: appointment-service-secret
                  key: DATABASE_URL
      containers:
        - name: appointment-service
          image: nexus-appointment-service:1.0-early
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
              name: http
          envFrom:
            - configMapRef:
                name: nexus-common-config
          env:
            - name: PORT
              value: '3002'
            - name: SERVICE_HTTP_PORT
              value: '3002'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: appointment-service-secret
                  key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service-svc
  namespace: nexus-service
  labels:
    app: appointment-service
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: 3002
      name: http
  selector:
    app: appointment-service
