apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: nexus-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      initContainers:
        - name: db-migration
          image: nexus/auth-service:1.0-early
          command: ['bunx', 'prisma', 'migrate', 'deploy']
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DATABASE_URL
      containers:
        - name: auth-service
          image: nexus-auth-service:1.0-early
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
              name: http
          envFrom:
            - configMapRef:
                name: nexus-common-config
          env:
            - name: PORT
              value: '3001'
            - name: SERVICE_HTTP_PORT
              value: '3001'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-svc
  namespace: nexus-service
  labels:
    app: auth-service
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      name: http
  selector:
    app: auth-service
