apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - tools/nats.yaml
  - tools/redis.yaml
  - observability/alloy.yaml
  - observability/grafana.yaml
  - observability/loki.yaml
  - observability/promtheus.yaml
  - observability/tempo.yaml
  - observability/tempo-configmap.yaml
  - observability/otel-collector.yaml
  - observability/prome-alert.yaml
