apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-common-config
  namespace: nexus-service
data:
  NODE_ENV: "production"
  NATS_SERVER: "nats://nats-svc.nexus-infra.svc.cluster.local:4222"
  REDIS_HOST: "redis-svc.nexus-infra.svc.cluster.local"
  REDIS_PORT: "6379"
