apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  namespace: nexus-service
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: nexus-healthcare-system
type: Opaque
stringData:
  NATS_USER: ""
  NATS_PASSWORD: ""
  NATS_TOKEN: ""
  REDIS_USERNAME: ""
  REDIS_PASSWORD: ""
  RESEND_API_KEY: ""
