apiVersion: v1
kind: Service
metadata:
  name: tempo-svc
  namespace: nexus-infra
  labels:
    app: tempo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3200
      targetPort: 3200
  selector:
    app: tempo
