apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-postgres
  namespace: nexus-service
  labels:
    app: billing-postgres
    app.kubernetes.io/name: billing-postgres
    app.kubernetes.io/part-of: nexus-healthcare-system
spec:
  serviceName: billing-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: billing-postgres
  template:
    metadata:
      labels:
        app: billing-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: billing-service-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-service-secret
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapRef:
                  name: billing-service-config
                  key: DB_NAME
          ports:
            - containerPort: 5432
              name: postgres
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            exec:
              command: ["cmd", "pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["cmd", "pg_isready", "-U", "postgres"]
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: billing-psql-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: billing-psql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: billing-postgres-svc
  namespace: nexus-service
  labels:
    app: billing-postgres
    app.kubernetes.io/name: billing-postgres
    app.kubernetes.io/part-of: nexus-healthcare-system
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: billing-postgres
