apiVersion: v1
kind: Service
metadata:
  name: pharmacy-service-svc
  namespace: nexus-service
  labels:
    app.kubernetes.io/name: pharmacy-service
    app.kubernetes.io/part-of: nexus-healthcare-system
spec:
  type: ClusterIP
  ports:
    - port: 5007
      targetPort: 5007
      name: http
    - port: 500057
      targetPort: 500057
      name: grpc
  selector:
    app: pharmacy-service
