apiVersion: apps/v1
kind: Deployment
metadata:
  name: ward-service
  namespace: nexus-service
  labels:
    app.kubernetes.io/name: ward-service
    app.kubernetes.io/part-of: nexus-healthcare-system
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ward-service
  template:
    metadata:
      labels:
        app: ward-service
    spec:
      initContainers:
        - name: db-migration
          image: nexus-ward-service:1.0-early
          imagePullPolicy: IfNotPresent
          command: ['bunx', 'prisma', 'migrate', 'deploy']
          envFrom:
            - configMapRef:
                name: ward-service-config
            - secretRef:
                name: ward-service-secret
      containers:
        - name: ward-service
          image: nexus-ward-service:1.0-early
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5009
              name: http
            - containerPort: 500059
              name: grpc
          envFrom:
            - configMapRef:
                name: nexus-common-config
            - configMapRef:
                name: ward-service-config
            - secretRef:
                name: ward-service-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 5009
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5009
            initialDelaySeconds: 15
            periodSeconds: 15
