apiVersion: v1
kind: Service
metadata:
  name: ward-service-svc
  namespace: nexus-service
  labels:
    app.kubernetes.io/name: ward-service
    app.kubernetes.io/part-of: nexus-healthcare-system
spec:
  type: ClusterIP
  ports:
    - port: 5009
      targetPort: 5009
      name: http
    - port: 500059
      targetPort: 500059
      name: grpc
  selector:
    app: ward-service
