apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: nexus-service
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: nexus-healthcare-system
type: Opaque
stringData:
  NATS_USER: ''
  NATS_PASSWORD: ''
  NATS_TOKEN: ''
  NATS_CLIENT_ID: ''
  REDIS_USERNAME: ''
  REDIS_PASSWORD: ''
