apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dashboard
  namespace: nexus-infra
  labels:
    app: grafana-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-dashboard
  template:
    metadata:
      labels:
        app: grafana-dashboard
    spec:
      containers:
        - name: grafana-dashboard
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "Isyawal161104Password"
