apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dashboard
  namespace: nexus-infra
  labels:
    app: grafana-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-dashboard
  template:
    metadata:
      labels:
        app: grafana-dashboard
    spec:
      nodeSelector:
        workload: system-infra
      containers:
        - name: grafana-dashboard
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 45
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 5
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: 'admin'
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: 'Isyawal161104Password'
