apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: nexus-infra
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      nodeSelector:
        workload: system-infra
      containers:
        - name: loki
          image: grafana/loki:2.9.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3100
              name: http
