apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: nexus-infra
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      nodeSelector:
        workload: system-infra
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.90.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4317
              name: grpc
            - containerPort: 4318
              name: http
