apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: nexus-service
spec:
  template:
    spec:
      containers:
        - name: billing-service
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
