apiVersion: v1
kind: Secret
metadata:
  name: appointment-service-secret
  namespace: nexus-service
  labels:
    app.kubernetes.io/name: appointment-service
    app.kubernetes.io/part-of: nexus-healthcare-system
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "Isyawal161104"
  DATABASE_URL: "postgresql://postgres:Isyawal161104@appointment-postgres-svc:5432/nh-appointment?schema=public"
  NATS_USER: ""
  NATS_PASSWORD: ""
  NATS_TOKEN: ""
  REDIS_USERNAME: ""
  REDIS_PASSWORD: ""
