// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import 'dotenv/config';
import type {} from 'prisma';

export default defineConfig({
  schema: './database/prisma/schema.prisma',
  migrations: {
    path: './database/prisma/migrations',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
