apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  namespace: nexus-infra
  labels:
    app: nats
spec:
  serviceName: nats-svc
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      nodeSelector:
        workload: system-infra
      containers:
        - name: nats
          image: nats:2.10-alpine
          args: ["-js", "-sd", "/data"]
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 8222
              name: monitor
          volumeMounts:
            - name: nats-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: nats-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
