apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: nexus-infra
  labels:
    app: postgres
spec:
  serviceName: postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nexus-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_MULTIPLE_DATABASES
              value: "auth-db,appointment-db,billing-db,emr-db,inventory-db,pharmacy-db,staff-db,ward-db"
          volumeMounts:
            - name: psql-data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init-databases.sh
              subPath: init-databases.sh
      volumes:
        - name: init-script
          configMap:
            name: postgres-init-script
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: psql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: nexus-infra
data:
  init-databases.sh: |
    #!/bin/bash
    set -e
    set -u

    function create_user_and_database() {
      local database=$1
      echo "  Creating database '$database'"
      psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
          CREATE DATABASE "$database";
          GRANT ALL PRIVILEGES ON DATABASE "$database" TO "$POSTGRES_USER";
    EOSQL
    }

    if [ -n "${POSTGRES_MULTIPLE_DATABASES:-}" ]; then
      echo "Multiple database creation requested: $POSTGRES_MULTIPLE_DATABASES"
      for db in $(echo $POSTGRES_MULTIPLE_DATABASES | tr ',' ' '); do
        create_user_and_database $db
      done
      echo "Multiple databases created successfully"
    fi
