apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-infra.yaml
  - namespace-service.yaml
  - security/default-deny.yaml
  - network/nats-service.yaml
  - network/redis-service.yaml
  - network/grafana-service.yaml
  - network/prometheus-service.yaml
  - network/loki-service.yaml
  - network/tempo-service.yaml
  - network/otel-service.yaml
  - network/alert-service.yaml
  - infra
