apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    :80 {
        log {
            output stdout
        }
        
        # Route to services. Example routes:
        handle /api/auth* {
            reverse_proxy auth-service:3000
        }
        
        # Default route to the api-gateway (nexus-health)
        handle * {
            reverse_proxy api-gateway:3000
        }
    }
